spring:
  datasource:
    url: jdbc:mysql://localhost:3310/db_facturacion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: bruma_mysql_facturacion
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp-relay.brevo.com
    port: 465
    username: ae8b25001@smtp-brevo.com
    password: ${SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false